# Generated by Django 3.1.7 on 2021-03-22 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=17)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='direcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(choices=[('Afg', 'Afganistán'), ('Alb', 'Albania'), ('Ale', 'Alemania'), ('And', 'Andorra'), ('Ang', 'Angola'), ('Ant', 'Antigua y Barbuda'), ('Ara', 'Arabia Saudita'), ('Arg', 'Argelia'), ('Arge', 'Argentina'), ('Arm', 'Armenia'), ('Aus', 'Australia'), ('Aust', 'Austria'), ('Aze', 'Azerbaiyán'), ('Bah', 'Bahamas'), ('Ban', 'Bangladés'), ('Barb', 'Barbados'), ('Bar', 'Baréin'), ('Bel', 'Bélgica'), ('Beli', 'Belice'), ('Ben', 'Benín'), ('Bie', 'Bielorrusia'), ('Bir', 'Birmania'), ('Bol', 'Bolivia'), ('Bos', 'Bosnia y Herzegovina'), ('Bot', 'Botsuana'), ('Bra', 'Brasil'), ('Bru', 'Brunéi'), ('Bul', 'Bulgaria'), ('Bur', 'Burkina Faso'), ('Buru', 'Burundi'), ('But', 'Bután'), ('Cab', 'Cabo Verde'), ('Camb', 'Camboya'), ('Cam', 'Camerún'), ('Can', 'Canadá'), ('Cat', 'Catar'), ('Cha', 'Chad'), ('Chi', 'Chile'), ('Chin', 'China'), ('Chip', 'Chipre'), ('Ciu', 'Ciudad del Vaticano'), ('Col', 'Colombia'), ('Com', 'Comoras'), ('Cor-n', 'Corea del Norte'), ('Cor-s', 'Corea del Sur'), ('Cos-mar', 'Costa de Marfil'), ('Cost', 'Costa Rica'), ('Cro', 'Croacia'), ('Cub', 'Cuba'), ('Din', 'Dinamarca'), ('Dom', 'Dominica'), ('Ecu', 'Ecuador'), ('Egi', 'Egipto'), ('El ', 'El Salvador'), ('Emi', 'Emiratos Árabes Unidos'), ('Eri', 'Eritrea'), ('Esl-ia', 'Eslovaquia'), ('Esl-nia', 'Eslovenia'), ('Esp', 'España'), ('Est-uni', 'Estados Unidos'), ('Est', 'Estonia'), ('Eti', 'Etiopía'), ('Fil', 'Filipinas'), ('Fin', 'Finlandia'), ('Fiy', 'Fiyi'), ('Fra', 'Francia'), ('Gab', 'Gabón'), ('Gam', 'Gambia'), ('Geo', 'Georgia'), ('Gha', 'Ghana'), ('Gra', 'Granada'), ('Gre', 'Grecia'), ('Gua', 'Guatemala'), ('Guy', 'Guyana'), ('Gui', 'Guinea'), ('Gui-ecu', 'Guinea ecuatorial'), ('Gui-bi', 'Guinea-Bisáu'), ('Hai', 'Haití'), ('Hon', 'Honduras'), ('Hun', 'Hungría'), ('Ind', 'India'), ('Ind', 'Indonesia'), ('Ira', 'Irak'), ('Irá', 'Irán'), ('Irl', 'Irlanda'), ('Isl', 'Islandia'), ('Isl', 'Islas Marshall'), ('Isl', 'Islas Salomón'), ('Isr', 'Israel'), ('Ita', 'Italia'), ('Jam', 'Jamaica'), ('Jap', 'Japón'), ('Jor', 'Jordania'), ('Kaz', 'Kazajistán'), ('Ken', 'Kenia'), ('Kir', 'Kirguistán'), ('Kir', 'Kiribati'), ('Kuw', 'Kuwait'), ('Lao', 'Laos'), ('Les', 'Lesoto'), ('Let', 'Letonia'), ('Líb', 'Líbano'), ('Lib', 'Liberia'), ('Lib', 'Libia'), ('Lie', 'Liechtenstein'), ('Lit', 'Lituania'), ('Lux', 'Luxemburgo'), ('Mad', 'Madagascar'), ('Mal', 'Malasia'), ('Mal', 'Malaui'), ('Mal', 'Maldivas'), ('Mal', 'Malí'), ('Mal', 'Malta'), ('Mar', 'Marruecos'), ('Mau', 'Mauricio'), ('Mau', 'Mauritania'), ('Méx', 'México'), ('Mic', 'Micronesia'), ('Mol', 'Moldavia'), ('Món', 'Mónaco'), ('Mon', 'Mongolia'), ('Mon', 'Montenegro'), ('Moz', 'Mozambique'), ('Nam', 'Namibia'), ('Nau', 'Nauru'), ('Nep', 'Nepal'), ('Nic', 'Nicaragua'), ('Níg', 'Níger'), ('Nig', 'Nigeria'), ('Nor', 'Noruega'), ('Nue', 'Nueva Zelanda'), ('Omá', 'Omán'), ('Paí', 'Países Bajos'), ('Pak', 'Pakistán'), ('Pal', 'Palaos'), ('Pan', 'Panamá'), ('Pap', 'Papúa Nueva Guinea'), ('Par', 'Paraguay'), ('Per', 'Perú'), ('Pol', 'Polonia'), ('Por', 'Portugal'), ('Rei', 'Reino Unido'), ('Rep', 'República Centroafricana'), ('Rep', 'República Checa'), ('Rep', 'República de Macedonia'), ('Rep', 'República del Congo'), ('Rep', 'República Democrática del Congo'), ('Rep', 'República Dominicana'), ('Rep', 'República Sudafricana'), ('Rua', 'Ruanda'), ('Rum', 'Rumanía'), ('Rus', 'Rusia'), ('Sam', 'Samoa'), ('San', 'San Cristóbal y Nieves'), ('San', 'San Marino'), ('San', 'San Vicente y las Granadinas'), ('San', 'Santa Lucía'), ('San', 'Santo Tomé y Príncipe'), ('Sen', 'Senegal'), ('Ser', 'Serbia'), ('Sey', 'Seychelles'), ('Sie', 'Sierra Leona'), ('Sin', 'Singapur'), ('Sir', 'Siria'), ('Som', 'Somalia'), ('Sri', 'Sri Lanka'), ('Sua', 'Suazilandia'), ('Sud', 'Sudán'), ('Sud', 'Sudán del Sur'), ('Sue', 'Suecia'), ('Sui', 'Suiza'), ('Sur', 'Surinam'), ('Tai', 'Tailandia'), ('Tan', 'Tanzania'), ('Tay', 'Tayikistán'), ('Tim', 'Timor Oriental'), ('Tog', 'Togo'), ('Ton', 'Tonga'), ('Tri', 'Trinidad y Tobago'), ('Tún', 'Túnez'), ('Tur', 'Turkmenistán'), ('Tur', 'Turquía'), ('Tuv', 'Tuvalu'), ('Ucr', 'Ucrania'), ('Uga', 'Uganda'), ('Uru', 'Uruguay'), ('Uzb', 'Uzbekistán'), ('Van', 'Vanuatu'), ('Ven', 'Venezuela'), ('Vie', 'Vietnam'), ('Yem', 'Yemen'), ('Yib', 'Yibuti'), ('Zam', 'Zambia'), ('Zim', 'Zimbabue')], max_length=40)),
                ('nombre_completo', models.CharField(help_text='Introduca su nombre y apellidos', max_length=40)),
                ('direccion1', models.CharField(help_text='Línea 1 de la dirección', max_length=40)),
                ('direccion2', models.CharField(help_text='Línea 2 de la dirección', max_length=40, null=True)),
                ('ciudad', models.CharField(help_text='Introduca su ciudad', max_length=40)),
                ('provincia', models.CharField(help_text='Introduca su provincia/región', max_length=40)),
                ('codigo_postal', models.CharField(help_text='Introduca su codigo postal', max_length=7)),
                ('numero_telefono', models.CharField(help_text='Introduca su numero de telefono', max_length=15)),
                ('notas', models.CharField(help_text='Añadir instrucciones de entrega', max_length=500, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apppeluqueria.clienteprofile')),
            ],
        ),
    ]
