# Generated by Django 3.1.7 on 2021-05-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppeluqueria', '0003_auto_20210517_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fecha',
            name='dia',
            field=models.DateField(null=True),
        ),
    ]
